spring:
  application:
    name: authService
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
  main:
    allow-bean-definition-overriding: true
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://database-2.cn2a20wwccoe.ap-southeast-2.rds.amazonaws.com:3306/ptproject
    username: root
    password: 123456aA
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 1111

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

ribbon:
  eureka:
    enabled: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

info:
  app:
    name: Auth Application
    description: This is a sample application about Auth.
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
