spring:
  application:
    name: gatewayService
server:
  port: 1112

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

ribbon:
  eureka:
    enabled: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
    org.springframework.cloud.netflix.zuul: DEBUG
    root: DEBUG

info:
  app:
    name: GateWay Application
    description: This is a sample application about GateWay.
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
#zuul:
#  routes:
#    userService:
#      path: /user/**
#      url: http://localhost:1113/api/user

zuul:
  routes:
    userService:
      path: /user/**
      service-id: userService

